primary_agent:
  llm: "gpt-3.5-turbo"
  llm_temperature: 0.0

sqlagent_configs:
  llm: "gpt-3.5-turbo"
  llm_temperature: 0.0

guiderag_configs:
  docs: "Notebooks\\vectorDocs"
  # vectordb: "data/airline_policy_vectordb"
  collection_name: guide-rag
  llm: gpt-4o-mini
  llm_temperature: 0.0
  embedding_model: text-embedding-3-small
  chunk_size: 50
  chunk_overlap: 10
  k: 10

tavily_configs:
  max_results: 2